### ISSUE TITLE
run yarn ERROR

### ISSUE THREAD

**Issue by lamick** [taoweicn/quiz-game#1]
/root/.node-gyp/12.13.1/include/node/v8.h:5426:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/binding.cpp:1:
../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before '>' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ')' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from /usr/include/c++/4.8.2/cassert:43:0,
                 from /root/.node-gyp/12.13.1/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:55,
                 from ../src/binding.cpp:1:
../../nan/nan_object_wrap.h: In destructor 'virtual Nan::ObjectWrap::~ObjectWrap()':
../../nan/nan_object_wrap.h:24:25: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(persistent().IsNearDeath());
                         ^
../../nan/nan_object_wrap.h: In static member function 'static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)':
../../nan/nan_object_wrap.h:127:26: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(wrap->handle_.IsNearDeath());
                          ^
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/data/github/quiz-game/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/github/quiz-game/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 3.10.107-1-tlinux2_kvm_guest-0048
gyp ERR! command "/usr/local/bin/node" "/data/github/quiz-game/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /data/github/quiz-game/node_modules/node-sass
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

**Comment by taoweicn** [comment]
It seems to be caused by the `node-sass` library, maybe you can refer to [this issue](https://github.com/nodejs/docker-node/issues/1149) to upgrade `node-sass` or downgrade `node`.
